/**
 * generated by Xtext 2.13.0
 */
package com.ufcg.compiladores.ide;

import com.google.inject.Injector;
import com.ufcg.compiladores.GoStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GoIdeSetup extends GoStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from GoRuntimeModule to Module"
      + "\nType mismatch: cannot convert from GoIdeModule to Module");
  }
}
