/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go.impl;

import com.ufcg.compiladores.go.GoPackage;
import com.ufcg.compiladores.go.binary_op;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>binary op</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.impl.binary_opImpl#getRel_op <em>Rel op</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.impl.binary_opImpl#getAdd_op <em>Add op</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.impl.binary_opImpl#getMul_op <em>Mul op</em>}</li>
 * </ul>
 *
 * @generated
 */
public class binary_opImpl extends MinimalEObjectImpl.Container implements binary_op
{
  /**
   * The default value of the '{@link #getRel_op() <em>Rel op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRel_op()
   * @generated
   * @ordered
   */
  protected static final String REL_OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRel_op() <em>Rel op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRel_op()
   * @generated
   * @ordered
   */
  protected String rel_op = REL_OP_EDEFAULT;

  /**
   * The default value of the '{@link #getAdd_op() <em>Add op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdd_op()
   * @generated
   * @ordered
   */
  protected static final String ADD_OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAdd_op() <em>Add op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdd_op()
   * @generated
   * @ordered
   */
  protected String add_op = ADD_OP_EDEFAULT;

  /**
   * The default value of the '{@link #getMul_op() <em>Mul op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMul_op()
   * @generated
   * @ordered
   */
  protected static final String MUL_OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMul_op() <em>Mul op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMul_op()
   * @generated
   * @ordered
   */
  protected String mul_op = MUL_OP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected binary_opImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.BINARY_OP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getRel_op()
  {
    return rel_op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRel_op(String newRel_op)
  {
    String oldRel_op = rel_op;
    rel_op = newRel_op;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.BINARY_OP__REL_OP, oldRel_op, rel_op));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAdd_op()
  {
    return add_op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAdd_op(String newAdd_op)
  {
    String oldAdd_op = add_op;
    add_op = newAdd_op;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.BINARY_OP__ADD_OP, oldAdd_op, add_op));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMul_op()
  {
    return mul_op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMul_op(String newMul_op)
  {
    String oldMul_op = mul_op;
    mul_op = newMul_op;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.BINARY_OP__MUL_OP, oldMul_op, mul_op));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.BINARY_OP__REL_OP:
        return getRel_op();
      case GoPackage.BINARY_OP__ADD_OP:
        return getAdd_op();
      case GoPackage.BINARY_OP__MUL_OP:
        return getMul_op();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.BINARY_OP__REL_OP:
        setRel_op((String)newValue);
        return;
      case GoPackage.BINARY_OP__ADD_OP:
        setAdd_op((String)newValue);
        return;
      case GoPackage.BINARY_OP__MUL_OP:
        setMul_op((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.BINARY_OP__REL_OP:
        setRel_op(REL_OP_EDEFAULT);
        return;
      case GoPackage.BINARY_OP__ADD_OP:
        setAdd_op(ADD_OP_EDEFAULT);
        return;
      case GoPackage.BINARY_OP__MUL_OP:
        setMul_op(MUL_OP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.BINARY_OP__REL_OP:
        return REL_OP_EDEFAULT == null ? rel_op != null : !REL_OP_EDEFAULT.equals(rel_op);
      case GoPackage.BINARY_OP__ADD_OP:
        return ADD_OP_EDEFAULT == null ? add_op != null : !ADD_OP_EDEFAULT.equals(add_op);
      case GoPackage.BINARY_OP__MUL_OP:
        return MUL_OP_EDEFAULT == null ? mul_op != null : !MUL_OP_EDEFAULT.equals(mul_op);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (rel_op: ");
    result.append(rel_op);
    result.append(", add_op: ");
    result.append(add_op);
    result.append(", mul_op: ");
    result.append(mul_op);
    result.append(')');
    return result.toString();
  }

} //binary_opImpl
