/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go.impl;

import com.ufcg.compiladores.go.GoPackage;
import com.ufcg.compiladores.go.rune_lit;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>rune lit</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.impl.rune_litImpl#getUnicode_value <em>Unicode value</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.impl.rune_litImpl#getByte_value <em>Byte value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class rune_litImpl extends MinimalEObjectImpl.Container implements rune_lit
{
  /**
   * The default value of the '{@link #getUnicode_value() <em>Unicode value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnicode_value()
   * @generated
   * @ordered
   */
  protected static final String UNICODE_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUnicode_value() <em>Unicode value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnicode_value()
   * @generated
   * @ordered
   */
  protected String unicode_value = UNICODE_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getByte_value() <em>Byte value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getByte_value()
   * @generated
   * @ordered
   */
  protected static final String BYTE_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getByte_value() <em>Byte value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getByte_value()
   * @generated
   * @ordered
   */
  protected String byte_value = BYTE_VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected rune_litImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.RUNE_LIT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUnicode_value()
  {
    return unicode_value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnicode_value(String newUnicode_value)
  {
    String oldUnicode_value = unicode_value;
    unicode_value = newUnicode_value;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.RUNE_LIT__UNICODE_VALUE, oldUnicode_value, unicode_value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getByte_value()
  {
    return byte_value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setByte_value(String newByte_value)
  {
    String oldByte_value = byte_value;
    byte_value = newByte_value;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.RUNE_LIT__BYTE_VALUE, oldByte_value, byte_value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.RUNE_LIT__UNICODE_VALUE:
        return getUnicode_value();
      case GoPackage.RUNE_LIT__BYTE_VALUE:
        return getByte_value();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.RUNE_LIT__UNICODE_VALUE:
        setUnicode_value((String)newValue);
        return;
      case GoPackage.RUNE_LIT__BYTE_VALUE:
        setByte_value((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.RUNE_LIT__UNICODE_VALUE:
        setUnicode_value(UNICODE_VALUE_EDEFAULT);
        return;
      case GoPackage.RUNE_LIT__BYTE_VALUE:
        setByte_value(BYTE_VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.RUNE_LIT__UNICODE_VALUE:
        return UNICODE_VALUE_EDEFAULT == null ? unicode_value != null : !UNICODE_VALUE_EDEFAULT.equals(unicode_value);
      case GoPackage.RUNE_LIT__BYTE_VALUE:
        return BYTE_VALUE_EDEFAULT == null ? byte_value != null : !BYTE_VALUE_EDEFAULT.equals(byte_value);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (unicode_value: ");
    result.append(unicode_value);
    result.append(", byte_value: ");
    result.append(byte_value);
    result.append(')');
    return result.toString();
  }

} //rune_litImpl
