/**
 * generated by Xtext 2.13.0
 */
package com.ufcg.compiladores.ui.contentassist;

import com.ufcg.compiladores.ui.contentassist.AbstractGoProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GoProposalProvider extends AbstractGoProposalProvider {
}
