/**
 * generated by Xtext 2.13.0
 */
package com.ufcg.compiladores;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GoRuntimeModule /* implements AbstractGoRuntimeModule  */{
}
