/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Channel Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufcg.compiladores.go.GoPackage#getChannelType()
 * @model
 * @generated
 */
public interface ChannelType extends EObject
{
} // ChannelType
