/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.ElementList#getKeyedElement <em>Keyed Element</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiladores.go.GoPackage#getElementList()
 * @model
 * @generated
 */
public interface ElementList extends EObject
{
  /**
   * Returns the value of the '<em><b>Keyed Element</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.KeyedElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Keyed Element</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyed Element</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getElementList_KeyedElement()
   * @model containment="true"
   * @generated
   */
  EList<KeyedElement> getKeyedElement();

} // ElementList
