/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.LiteralValue#getElementList <em>Element List</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiladores.go.GoPackage#getLiteralValue()
 * @model
 * @generated
 */
public interface LiteralValue extends Element, Key
{
  /**
   * Returns the value of the '<em><b>Element List</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.ElementList}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element List</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getLiteralValue_ElementList()
   * @model containment="true"
   * @generated
   */
  EList<ElementList> getElementList();

} // LiteralValue
