/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufcg.compiladores.go.GoPackage#getMapType()
 * @model
 * @generated
 */
public interface MapType extends LiteralType
{
} // MapType
