/**
 * generated by Xtext 2.13.0
 */
package com.ufcg.compiladores.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.ParameterDecl#getParameterDecl <em>Parameter Decl</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiladores.go.GoPackage#getParameterDecl()
 * @model
 * @generated
 */
public interface ParameterDecl extends ParameterList
{
  /**
   * Returns the value of the '<em><b>Parameter Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter Decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter Decl</em>' containment reference.
   * @see #setParameterDecl(ParameterDecl)
   * @see com.ufcg.compiladores.go.GoPackage#getParameterDecl_ParameterDecl()
   * @model containment="true"
   * @generated
   */
  ParameterDecl getParameterDecl();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ParameterDecl#getParameterDecl <em>Parameter Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter Decl</em>' containment reference.
   * @see #getParameterDecl()
   * @generated
   */
  void setParameterDecl(ParameterDecl value);

} // ParameterDecl
