/**
 * generated by Xtext 2.13.0
 */
package com.ufcg.compiladores.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pointer Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufcg.compiladores.go.GoPackage#getPointerType()
 * @model
 * @generated
 */
public interface PointerType extends TypeLit
{
} // PointerType
