/**
 * generated by Xtext 2.13.0
 */
package com.ufcg.compiladores.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Receiver Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufcg.compiladores.go.GoPackage#getReceiverType()
 * @model
 * @generated
 */
public interface ReceiverType extends MethodExpr
{
} // ReceiverType
