/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Souce File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.SouceFile#getPackageClause <em>Package Clause</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.SouceFile#getImportDecl <em>Import Decl</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.SouceFile#getTopLevelDecl <em>Top Level Decl</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiladores.go.GoPackage#getSouceFile()
 * @model
 * @generated
 */
public interface SouceFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Package Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Package Clause</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package Clause</em>' containment reference.
   * @see #setPackageClause(PackageClause)
   * @see com.ufcg.compiladores.go.GoPackage#getSouceFile_PackageClause()
   * @model containment="true"
   * @generated
   */
  PackageClause getPackageClause();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.SouceFile#getPackageClause <em>Package Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package Clause</em>' containment reference.
   * @see #getPackageClause()
   * @generated
   */
  void setPackageClause(PackageClause value);

  /**
   * Returns the value of the '<em><b>Import Decl</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.ImportDecl}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Import Decl</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Decl</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getSouceFile_ImportDecl()
   * @model containment="true"
   * @generated
   */
  EList<ImportDecl> getImportDecl();

  /**
   * Returns the value of the '<em><b>Top Level Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Top Level Decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Top Level Decl</em>' containment reference.
   * @see #setTopLevelDecl(TopLevelDecl)
   * @see com.ufcg.compiladores.go.GoPackage#getSouceFile_TopLevelDecl()
   * @model containment="true"
   * @generated
   */
  TopLevelDecl getTopLevelDecl();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.SouceFile#getTopLevelDecl <em>Top Level Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Top Level Decl</em>' containment reference.
   * @see #getTopLevelDecl()
   * @generated
   */
  void setTopLevelDecl(TopLevelDecl value);

} // SouceFile
