/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Lit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.TypeLit#getTypeLitLinha <em>Type Lit Linha</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.TypeLit#getStructType <em>Struct Type</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.TypeLit#getPointerType <em>Pointer Type</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.TypeLit#getFunctionType <em>Function Type</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.TypeLit#getInterfaceType <em>Interface Type</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.TypeLit#getMapType <em>Map Type</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.TypeLit#getChannelType <em>Channel Type</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiladores.go.GoPackage#getTypeLit()
 * @model
 * @generated
 */
public interface TypeLit extends Type
{
  /**
   * Returns the value of the '<em><b>Type Lit Linha</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.TypeLitLinha}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Lit Linha</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Lit Linha</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getTypeLit_TypeLitLinha()
   * @model containment="true"
   * @generated
   */
  EList<TypeLitLinha> getTypeLitLinha();

  /**
   * Returns the value of the '<em><b>Struct Type</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.StructType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Struct Type</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Struct Type</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getTypeLit_StructType()
   * @model containment="true"
   * @generated
   */
  EList<StructType> getStructType();

  /**
   * Returns the value of the '<em><b>Pointer Type</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.PointerType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pointer Type</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pointer Type</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getTypeLit_PointerType()
   * @model containment="true"
   * @generated
   */
  EList<PointerType> getPointerType();

  /**
   * Returns the value of the '<em><b>Function Type</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.FunctionType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Type</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Type</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getTypeLit_FunctionType()
   * @model containment="true"
   * @generated
   */
  EList<FunctionType> getFunctionType();

  /**
   * Returns the value of the '<em><b>Interface Type</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.InterfaceType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Interface Type</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface Type</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getTypeLit_InterfaceType()
   * @model containment="true"
   * @generated
   */
  EList<InterfaceType> getInterfaceType();

  /**
   * Returns the value of the '<em><b>Map Type</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.MapType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Map Type</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map Type</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getTypeLit_MapType()
   * @model containment="true"
   * @generated
   */
  EList<MapType> getMapType();

  /**
   * Returns the value of the '<em><b>Channel Type</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiladores.go.ChannelType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channel Type</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel Type</em>' containment reference list.
   * @see com.ufcg.compiladores.go.GoPackage#getTypeLit_ChannelType()
   * @model containment="true"
   * @generated
   */
  EList<ChannelType> getChannelType();

} // TypeLit
