/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufcg.compiladores.go.GoPackage#getVarDecl()
 * @model
 * @generated
 */
public interface VarDecl extends Declaration
{
} // VarDecl
